<?php

/**
 * Implementation of hook_theme().
 */
function ting_search_autocomplete_theme() {
  return array();
}

/**
 * Implementation of hook_menu().
 */
function ting_search_autocomplete_menu() {
  $items = array();

  $items['ting/autocomplete'] = array(
    'title' => 'Ting search autocomplete',
    'description' => 'Returns a list of suggestions to use for autocompletion',
    'access arguments' => array('search content'),
    'page callback' => 'ting_search_autocomplete_js',
    'type' => MENU_CALLBACK,
    'file' => 'ting_search_autocomplete.pages.inc',
  );

  return $items;
}

/**
 * Implementation of hook_trampoline().
 */
function ting_search_autocomplete_trampoline() {
  $includes = array();

  //Include Ting client
  $ting_files = array(
    'TingClient.php',
    'exception/TingClientException.php',
    'adapter/TingClientRequestAdapter.php',
    'log/TingClientLogger.php',
    'log/TingClientDrupalDebugLogger.php',
    'log/TingClientDrupalWatchDogLogger.php',
    'log/TingClientVoidLogger.php',
    'request/TingClientRequest.php',
    'request/TingClientSearchRequest.php',
    'request/TingClientCollectionRequest.php',
    'request/TingClientObjectRecommendationRequest.php',
    'request/TingClientObjectRequest.php',
    'request/TingClientRequestFactory.php',
    'request/TingClientScanRequest.php',
    'request/TingClientSpellRequest.php',
    'result/object/TingClientObject.php',
    'result/object/TingClientObjectCollection.php',
    'result/object/data/TingClientObjectData.php',
    'result/recommendation/TingClientObjectRecommendation.php',
    'result/scan/TingClientScanResult.php',
    'result/scan/TingClientScanTerm.php',
    'result/search/TingClientFacetResult.php',
    'result/search/TingClientSearchResult.php',
    'result/spell/TingClientSpellSuggestion.php',
  );
  $ting_path = drupal_get_path('module', 'ting');
  foreach ($ting_files as $file) {
    $includes[] = $ting_path . '/lib/ting-client/lib/' . $file;
  }

  //Include NanoSOAP required by Ting client
  $includes[] = drupal_get_path('module', 'nanosoap') . '/nanosoap.inc';

  $items = array();
  $items['ting/autocomplete'] = array(
    'includes' => $includes,
  );
  return $items;
}

/**
 * Implementation of hook_flush_caches().
 */
function ting_search_autocomplete_flush_caches() {
  return array('cache_ting_search_autocomplete');
}

/**
 * Alter the Ting search form to add autocomplete.
 */
function ting_search_autocomplete_form_ting_search_form_alter(&$form, &$form_state) {
  //TODO should this be moved to another hook?
  static $includes_loaded;
  if (!isset($includes_loaded)) {
    $basePath = drupal_get_path('module', 'ting');
    drupal_add_js($basePath . '/js/jquery-autocomplete-1.0.2-mod/jquery.autocomplete.min.js', 'module', 'footer', TRUE);
    drupal_add_css($basePath . '/js/jquery-autocomplete-1.0.2-mod/jquery.autocomplete.css', 'module');

    $modulePath = drupal_get_path('module', 'ting_search_autocomplete');
    drupal_add_js($modulePath.'/js/ting_search_autocomplete.js', 'module', 'footer', TRUE);

    $autocomple_path = (module_exists('trampoline')) ? trampoline_url('ting/autocomplete') : url('ting/autocomplete');
    drupal_add_js(array('tingSearchAutocomplete' => array('path' => $autocomple_path)), 'setting');
    drupal_add_css($modulePath.'/css/ting_search_autocomplete.css', 'module');

    $includes_loaded = true;
  }

  $form['keys']['#attributes'] = array('class' => 'ting-autocomplete');
}
