<?php

/**
 * Implementation of hook_menu().
 */
function ting_availability_menu() {
  $items = array();

  $items['ting/availability/item/%'] = array(
    'title' => 'Get item availability',
    'description' => 'Get item availability for items.',
    'page callback' => 'ting_availability_item_page',
    'page arguments' => array(3),
    'access arguments' => array('access content'),
  );

  $items['ting/availability/item/%/details'] = array(
    'title' => 'Get item availability details',
    'description' => 'Get all details for items. Availability, location, etc.',
    'page callback' => 'ting_availability_item_details_page',
    'page arguments' => array(3),
    'access arguments' => array('access content'),
  );

  return $items;
}

/**
 * Implementation of hook_ting_add_js().
 */
function ting_availability_ting_add_js($type) {
  $path = drupal_get_path('module', 'ting_availability') . '/js';

  switch ($type) {
    case 'ting_object_view':
      drupal_add_js($path . '/ting.availability.js', 'module', 'footer', TRUE);
      drupal_add_js($path . '/ting.availability.ting_object_view.js', 'module', 'footer', TRUE);
      break;
    case 'ting_collection_view':
      drupal_add_js($path . '/ting.availability.js', 'module', 'footer', TRUE);
      drupal_add_js('$(function(){Drupal.tingAvailability.get_details(Drupal.tingAvailability.updateStatus)});', 'inline', 'footer', TRUE);
      break;
    case 'ting_search_view':
      drupal_add_js($path . '/ting.availability.js', 'module', 'footer', TRUE);
      break;
  }
}

/**
 * Implementation of hook_requirements().
 */
function ting_availability_requirements($phase) {
  $requrements = array();

  if ($phase == 'runtime') {
    $reservation_provider = ding_provider_description('availability');

    $requrements['ding_availability'] = array(
      'title' => t('Ding availability'),
      'severity' => $reservation_provider ? REQUIREMENT_INFO : REQUIREMENT_WARNING,
      'value' => $reservation_provider,
      'description' => $reservation_provider ? t('OK'): t('No reservation provider active.'),
    );
  }

  return $requrements;
}

/**
 * AHAH callback to get library item availability.
 *
 * @param string $input
 *    Input string, one or more library system item IDs, comma-separated.
 */
function ting_availability_item_page($provider_id) {
  $items = ding_provider_invoke('availability', 'items', explode(',', $provider_id));

  // We are returning JavaScript, so tell the browser.
  drupal_set_header('Content-Type: application/json; charset=utf-8');
  echo json_encode($items);
  return;
}

/**
 * AHAH callback to get library item details.
 *
 * @param string $input
 *    Input string, one or more library system item IDs, comma-separated.
 */
function ting_availability_item_details_page($provider_id) {
  // $data = module_invoke_all('ting_availability_item_details', $provider_id);

  // $items = (!empty($data['records'])) ? $data['records'] : array();

  $items = ding_provider_invoke('availability', 'details', explode(',', $provider_id));
  // We are returning JavaScript, so tell the browser.
  drupal_set_header('Content-Type: application/json; charset=utf-8');
  echo json_encode($items);
  return;
}

